# Using the main rust docker image.
FROM rust as build
# Copy app into docker image
COPY . /app
# Setting working directory
WORKDIR /app
# Ensure SQLX builds in offline mode.
ENV SQLX_OFFLINE=true
# Build the app
RUN cargo build --release
# use google distroless as runtime image.
FROM gcr.io/distroless/cc-debian12
# Copy app from builder
COPY --from=build /app/target/release/tick-mark-digital /app/tick-mark-digital
# Copy migration script
COPY migrations ./migrations
WORKDIR /app
# Starting the application
#ENTRYPOINT ["./tick-mark-digital"]
CMD ["./tick-mark-digital"]
